In [578]:
import pandas as pd
import numpy as np

1.	Descarga el dataset “Notas de estudiantes.csv” (o un dataset entregado por el docente).
2.	Carga el dataset en un notebook.

In [579]:
df = pd.read_csv('Notas_de_estudiantes.csv')

3.	Identifica los siguientes problemas:

    a) Valores faltantes.
    
	b) Duplicados.

	c) Outliers (por ejemplo: notas menores a 1.0 o mayores a 7.0).

In [580]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID_Estudiante  195 non-null    int64
 1   Nombre         187 non-null    str
 2   Edad           185 non-null    float64
 3   Carrera        195 non-null    str
 4   Seccion        195 non-null    str
 5   Ciudad         187 non-null    str
 6   Nota           185 non-null    float64
 7   Asistencia     190 non-null    float64
dtypes: float64(3), int64(1), str(4)
memory usage: 12.3 KB

In [581]:
df.describe()

       ID_Estudiante        Edad        Nota  Asistencia
count     195.000000  185.000000  185.000000  190.000000
mean       88.000000   22.329730    5.171892   83.805263
std        52.546298    6.561948    1.248290    9.421296
min         1.000000   16.000000   -1.000000   57.000000
25%        43.500000   20.000000    4.500000   77.250000
50%        87.000000   22.000000    5.200000   84.000000
75%       133.500000   23.000000    5.900000   91.000000
max       180.000000   99.000000   10.000000  100.000000

Tenemos 195 registros.

In [582]:
# Eliminar nulos
datos_faltantes = {}
columns = df.columns

print(df.isnull().sum())

ID_Estudiante     0
Nombre            8
Edad             10
Carrera           0
Seccion           0
Ciudad            8
Nota             10
Asistencia        5
dtype: int64

In [583]:
# Quitar Duplicados
print('Cantidad de registros duplicados:', df.duplicated().sum())
df_clean = df_clean.drop_duplicates()

Cantidad de registros duplicados: 15

In [584]:
# Notas fuera de rango
mask_notas = (df_clean['Nota'].between(1,7)) & (~df_clean['Nota'].isna())

print(f'Hay un total de {len(df_clean[~mask_notas])} notas fuera del rango entre 1 y 7')
df_clean.loc[~mask_notas, 'Nota'] = pd.NA

Hay un total de 0 notas fuera del rango entre 1 y 7

In [585]:
# Tratar nulos

# Nombre
df_clean['Nombre'] = df_clean['Nombre'].fillna('No Informado')

# Edad
df_clean['Edad'] = df_clean['Edad'].fillna(df_clean['Edad'].mean())

# Nota
df_clean['Nota'] = df_clean['Nota'].fillna(df_clean['Nota'].mean())

# Asistencia
df_clean['Asistencia'] = df_clean['Asistencia'].fillna(df_clean['Asistencia'].mean())

df_clean['Ciudad'] = df_clean['Ciudad'].fillna(df_clean['Ciudad'].mode()[0])

df_clean.isna().sum()

ID_Estudiante    0
Nombre           0
Edad             0
Carrera          0
Seccion          0
Ciudad           0
Nota             0
Asistencia       0
False            0
dtype: int64

In [586]:
df_clean.describe()

       ID_Estudiante        Edad        Nota  Asistencia
count     174.000000  174.000000  174.000000  174.000000
mean       90.804598   22.274390    5.175000   83.698225
std        52.081603    6.709777    0.852445    9.310200
min         1.000000   16.000000    2.400000   57.000000
25%        46.250000   20.000000    4.600000   78.000000
50%        90.500000   22.000000    5.175000   84.000000
75%       135.750000   23.000000    5.875000   90.000000
max       180.000000   99.000000    7.000000  100.000000

In [587]:
# Normalizar ciudad
df_clean['Ciudad'] = df_clean['Ciudad'].str.capitalize()
df_clean['Ciudad'].unique()
df_clean['Ciudad' == 'Stgo'] = 'Santiago'
df_clean['Ciudad'] = df_clean['Ciudad'].replace('Stgo', 'Santiago')
df_clean['Ciudad'].unique()

<StringArray>
['Concepción', 'Temuco', 'Santiago', 'Valparaíso', 'La serena',
 'Puerto montt']
Length: 6, dtype: str

In [588]:
df_clean.info()

<class 'pandas.DataFrame'>
Index: 174 entries, 0 to 194
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID_Estudiante  174 non-null    int64
 1   Nombre         174 non-null    str
 2   Edad           174 non-null    float64
 3   Carrera        174 non-null    str
 4   Seccion        174 non-null    str
 5   Ciudad         174 non-null    str
 6   Nota           174 non-null    float64
 7   Asistencia     174 non-null    float64
 8   False          174 non-null    str
dtypes: float64(3), int64(1), str(5)
memory usage: 13.6 KB

In [589]:
df_clean.describe()

       ID_Estudiante        Edad        Nota  Asistencia
count     174.000000  174.000000  174.000000  174.000000
mean       90.804598   22.274390    5.175000   83.698225
std        52.081603    6.709777    0.852445    9.310200
min         1.000000   16.000000    2.400000   57.000000
25%        46.250000   20.000000    4.600000   78.000000
50%        90.500000   22.000000    5.175000   84.000000
75%       135.750000   23.000000    5.875000   90.000000
max       180.000000   99.000000    7.000000  100.000000