### Metodos en DataFrames para limpieza

* isnull(): Devuelve True o False si el valor es null
* duplicated(): Devuelve True o False si el valor esta duplicado
* drop_duplicated(): Elimina los registros duplicados

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Nombre": ["Juan", "Maria", "Juan", None],
    "Edad": [20, None, 20, 22],
    "Nota": [5.0, 6.5, 5.0, None]
})
display(df)

df['Edad'] = df['Edad'].fillna(df['Edad'].mean())
print("="*50, "\nNulos de Edad como Promedio de Edad")
display(df)

df['Nota'] = df['Nota'].fillna(df['Nota'].mean())
print("="*50, "\nNulos de Nota como Promedio de Nota")
display(df)

df = df.dropna()
print("="*50, "\nEliminación de Nulos")
display(df)

df = df.drop_duplicates()
print("="*50, "\nEliminacion de duplicados")
display(df)

  Nombre  Edad  Nota
0   Juan  20.0   5.0
1  Maria   NaN   6.5
2   Juan  20.0   5.0
3    NaN  22.0   NaN

==================================================
Nulos de Edad como Promedio de Edad

  Nombre       Edad  Nota
0   Juan  20.000000   5.0
1  Maria  20.666667   6.5
2   Juan  20.000000   5.0
3    NaN  22.000000   NaN

==================================================
Nulos de Nota como Promedio de Nota

  Nombre       Edad  Nota
0   Juan  20.000000   5.0
1  Maria  20.666667   6.5
2   Juan  20.000000   5.0
3    NaN  22.000000   5.5

==================================================
Eliminación de Nulos

  Nombre       Edad  Nota
0   Juan  20.000000   5.0
1  Maria  20.666667   6.5
2   Juan  20.000000   5.0

==================================================
Eliminacion de duplicados

  Nombre       Edad  Nota
0   Juan  20.000000   5.0
1  Maria  20.666667   6.5